In [1]:
import pandas as pd
import numpy as np

In [2]:
dataFrame=pd.read_csv('D:/Urban-Traffic-and-Parking-Analysis-using-LSTM-Autoencoders-and-Reinforcement-Learning/Dataset/synthetic_TEMPORAL.csv')

In [3]:
dataFrame.head()

,u,v,u_lat,u_lon,v_lat,v_lon,length_m,timestamp,hour,day_of_week,current_speed,free_flow_speed,congestion,travel_time_sec,rain,incident
0,245654691.0,1.034966e+09,18.9462,72.832,18.9472,72.8333,181.0757,2024-01-01 00:00:00,0,0,31.9352,40.0,0.2016,20.4124,0.0,0.0
1,245654691.0,1.034966e+09,18.9462,72.832,18.9472,72.8333,181.0757,2024-01-01 01:00:00,1,0,27.6883,40.0,0.3078,23.5433,0.0,0.0
2,245654691.0,1.034966e+09,18.9462,72.832,18.9472,72.8333,181.0757,2024-01-01 02:00:00,2,0,24.8180,40.0,0.3795,26.2661,0.0,0.0
3,245654691.0,1.034966e+09,18.9462,72.832,18.9472,72.8333,181.0757,2024-01-01 03:00:00,3,0,23.0393,40.0,0.4240,28.2940,0.0,0.0
4,245654691.0,1.034966e+09,18.9462,72.832,18.9472,72.8333,181.0757,2024-01-01 04:00:00,4,0,22.0214,40.0,0.4495,29.6017,0.0,0.0

In [4]:
len(dataFrame)

24176712

In [5]:
dataFrame=dataFrame.sort_values(by=["u","v","timestamp"])

In [6]:
dataFrame.head()

,u,v,u_lat,u_lon,v_lat,v_lon,length_m,timestamp,hour,day_of_week,current_speed,free_flow_speed,congestion,travel_time_sec,rain,incident
14616672,30610511.0,1.541914e+09,19.1925,73.0961,19.1926,73.096,9.2531,2024-01-01 00:00:00,0,0,30.6618,40.0,0.2335,1.0864,0.0,0.0
14616673,30610511.0,1.541914e+09,19.1925,73.0961,19.1926,73.096,9.2531,2024-01-01 01:00:00,1,0,25.2321,40.0,0.3692,1.3202,0.0,0.0
14616674,30610511.0,1.541914e+09,19.1925,73.0961,19.1926,73.096,9.2531,2024-01-01 02:00:00,2,0,21.7774,40.0,0.4556,1.5296,0.0,0.0
14616675,30610511.0,1.541914e+09,19.1925,73.0961,19.1926,73.096,9.2531,2024-01-01 03:00:00,3,0,19.7046,40.0,0.5074,1.6905,0.0,0.0
14616676,30610511.0,1.541914e+09,19.1925,73.0961,19.1926,73.096,9.2531,2024-01-01 04:00:00,4,0,18.6461,40.0,0.5338,1.7865,0.0,0.0

In [7]:
dataFrame['hour_sine']=np.sin(2*np.pi*dataFrame['hour']/24)
dataFrame['hour_cos']=np.cos(2*np.pi*dataFrame['hour']/24)
dataFrame['day_sin']=np.sin(2*np.pi*dataFrame['day_of_week']/7)
dataFrame['day_cos']=np.cos(2*np.pi*dataFrame['day_of_week']/7)

In [ ]:
from sklearn.preprocessing import RobustScaler
tt_scaler  = RobustScaler()
len_scaler = RobustScaler()

In [8]:
# cols=['travel_time_sec','length_m']
# dataFrame[cols]=scaler.fit_transform(dataFrame[cols])
dataFrame['travel_time_log']=np.log1p(dataFrame['travel_time_sec'])

In [9]:
dataFrame['length_log']=np.log1p(dataFrame['length_m'])
dataFrame["speed_ratio"] = (dataFrame["current_speed"] / dataFrame["free_flow_speed"]).clip(0.0, 1.0)
dataFrame.head()

,u,v,u_lat,u_lon,v_lat,v_lon,length_m,timestamp,hour,day_of_week,...,travel_time_sec,rain,incident,hour_sine,hour_cos,day_sin,day_cos,travel_time_log,length_log,speed_ratio
14616672,30610511.0,1.541914e+09,19.1925,73.0961,19.1926,73.096,9.2531,2024-01-01 00:00:00,0,0,...,1.0864,0.0,0.0,0.000000,1.000000,0.0,1.0,0.735440,2.32758,0.766545
14616673,30610511.0,1.541914e+09,19.1925,73.0961,19.1926,73.096,9.2531,2024-01-01 01:00:00,1,0,...,1.3202,0.0,0.0,0.258819,0.965926,0.0,1.0,0.841653,2.32758,0.630802
14616674,30610511.0,1.541914e+09,19.1925,73.0961,19.1926,73.096,9.2531,2024-01-01 02:00:00,2,0,...,1.5296,0.0,0.0,0.500000,0.866025,0.0,1.0,0.928061,2.32758,0.544435
14616675,30610511.0,1.541914e+09,19.1925,73.0961,19.1926,73.096,9.2531,2024-01-01 03:00:00,3,0,...,1.6905,0.0,0.0,0.707107,0.707107,0.0,1.0,0.989727,2.32758,0.492615
14616676,30610511.0,1.541914e+09,19.1925,73.0961,19.1926,73.096,9.2531,2024-01-01 04:00:00,4,0,...,1.7865,0.0,0.0,0.866025,0.500000,0.0,1.0,1.024786,2.32758,0.466153

In [ ]:
# dataFrame['speed_ratio']=dataFrame['current_speed']/dataFrame['free_flow_speed']

In [10]:
dataFrame=dataFrame.drop(['travel_time_sec','u_lat','v_lat','v_lon','u_lon'],axis=1)
dataFrame.head()

,u,v,length_m,timestamp,hour,day_of_week,current_speed,free_flow_speed,congestion,rain,incident,hour_sine,hour_cos,day_sin,day_cos,travel_time_log,length_log,speed_ratio
14616672,30610511.0,1.541914e+09,9.2531,2024-01-01 00:00:00,0,0,30.6618,40.0,0.2335,0.0,0.0,0.000000,1.000000,0.0,1.0,0.735440,2.32758,0.766545
14616673,30610511.0,1.541914e+09,9.2531,2024-01-01 01:00:00,1,0,25.2321,40.0,0.3692,0.0,0.0,0.258819,0.965926,0.0,1.0,0.841653,2.32758,0.630802
14616674,30610511.0,1.541914e+09,9.2531,2024-01-01 02:00:00,2,0,21.7774,40.0,0.4556,0.0,0.0,0.500000,0.866025,0.0,1.0,0.928061,2.32758,0.544435
14616675,30610511.0,1.541914e+09,9.2531,2024-01-01 03:00:00,3,0,19.7046,40.0,0.5074,0.0,0.0,0.707107,0.707107,0.0,1.0,0.989727,2.32758,0.492615
14616676,30610511.0,1.541914e+09,9.2531,2024-01-01 04:00:00,4,0,18.6461,40.0,0.5338,0.0,0.0,0.866025,0.500000,0.0,1.0,1.024786,2.32758,0.466153

In [11]:
import os

OUTPUT_FILE = "lstm_dataset_1.csv"
BATCH_SIZE = 50_000  # tune this (50k–500k depending on RAM)

if os.path.exists(OUTPUT_FILE):
    os.remove(OUTPUT_FILE)

def save_in_batches(dataFrame):
    total_rows = len(dataFrame)
    
    for start in range(0, total_rows, BATCH_SIZE):
        end = start + BATCH_SIZE
        batch = dataFrame.iloc[start:end]

        # First batch → write normally
        if start == 0:
            batch.to_csv(OUTPUT_FILE, index=False, mode='w')
        else:
            batch.to_csv(OUTPUT_FILE, index=False, mode='a', header=False)

        print(f"Saved rows {start} → {end}")

# Example usage
# df = your 24M dataframe
save_in_batches(dataFrame)

Saved rows 0 → 50000
Saved rows 50000 → 100000
Saved rows 100000 → 150000
Saved rows 150000 → 200000
Saved rows 200000 → 250000
Saved rows 250000 → 300000
Saved rows 300000 → 350000
Saved rows 350000 → 400000
Saved rows 400000 → 450000
Saved rows 450000 → 500000
Saved rows 500000 → 550000
Saved rows 550000 → 600000
Saved rows 600000 → 650000
Saved rows 650000 → 700000
Saved rows 700000 → 750000
Saved rows 750000 → 800000
Saved rows 800000 → 850000
Saved rows 850000 → 900000
Saved rows 900000 → 950000
Saved rows 950000 → 1000000
Saved rows 1000000 → 1050000
Saved rows 1050000 → 1100000
Saved rows 1100000 → 1150000
Saved rows 1150000 → 1200000
Saved rows 1200000 → 1250000
Saved rows 1250000 → 1300000
Saved rows 1300000 → 1350000
Saved rows 1350000 → 1400000
Saved rows 1400000 → 1450000
Saved rows 1450000 → 1500000
Saved rows 1500000 → 1550000
Saved rows 1550000 → 1600000
Saved rows 1600000 → 1650000
Saved rows 1650000 → 1700000
Saved rows 1700000 → 1750000
Saved rows 1750000 → 1800000
Saved rows 1800000 → 1850000
Saved rows 1850000 → 1900000
Saved rows 1900000 → 1950000
Saved rows 1950000 → 2000000
Saved rows 2000000 → 2050000
Saved rows 2050000 → 2100000
Saved rows 2100000 → 2150000
Saved rows 2150000 → 2200000
Saved rows 2200000 → 2250000
Saved rows 2250000 → 2300000
Saved rows 2300000 → 2350000
Saved rows 2350000 → 2400000
Saved rows 2400000 → 2450000
Saved rows 2450000 → 2500000
Saved rows 2500000 → 2550000
Saved rows 2550000 → 2600000
Saved rows 2600000 → 2650000
Saved rows 2650000 → 2700000
Saved rows 2700000 → 2750000
Saved rows 2750000 → 2800000
Saved rows 2800000 → 2850000
Saved rows 2850000 → 2900000
Saved rows 2900000 → 2950000
Saved rows 2950000 → 3000000
Saved rows 3000000 → 3050000
Saved rows 3050000 → 3100000
Saved rows 3100000 → 3150000
Saved rows 3150000 → 3200000
Saved rows 3200000 → 3250000
Saved rows 3250000 → 3300000
Saved rows 3300000 → 3350000
Saved rows 3350000 → 3400000
Saved rows 3400000 → 3450000
Saved rows 3450000 → 3500000
Saved rows 3500000 → 3550000
Saved rows 3550000 → 3600000
Saved rows 3600000 → 3650000
Saved rows 3650000 → 3700000
Saved rows 3700000 → 3750000
Saved rows 3750000 → 3800000
Saved rows 3800000 → 3850000
Saved rows 3850000 → 3900000
Saved rows 3900000 → 3950000
Saved rows 3950000 → 4000000
Saved rows 4000000 → 4050000
Saved rows 4050000 → 4100000
Saved rows 4100000 → 4150000
Saved rows 4150000 → 4200000
Saved rows 4200000 → 4250000
Saved rows 4250000 → 4300000
Saved rows 4300000 → 4350000
Saved rows 4350000 → 4400000
Saved rows 4400000 → 4450000
Saved rows 4450000 → 4500000
Saved rows 4500000 → 4550000
Saved rows 4550000 → 4600000
Saved rows 4600000 → 4650000
Saved rows 4650000 → 4700000
Saved rows 4700000 → 4750000
Saved rows 4750000 → 4800000
Saved rows 4800000 → 4850000
Saved rows 4850000 → 4900000
Saved rows 4900000 → 4950000
Saved rows 4950000 → 5000000
Saved rows 5000000 → 5050000
Saved rows 5050000 → 5100000
Saved rows 5100000 → 5150000
Saved rows 5150000 → 5200000
Saved rows 5200000 → 5250000
Saved rows 5250000 → 5300000
Saved rows 5300000 → 5350000
Saved rows 5350000 → 5400000
Saved rows 5400000 → 5450000
Saved rows 5450000 → 5500000
Saved rows 5500000 → 5550000
Saved rows 5550000 → 5600000
Saved rows 5600000 → 5650000
Saved rows 5650000 → 5700000
Saved rows 5700000 → 5750000
Saved rows 5750000 → 5800000
Saved rows 5800000 → 5850000
Saved rows 5850000 → 5900000
Saved rows 5900000 → 5950000
Saved rows 5950000 → 6000000
Saved rows 6000000 → 6050000
Saved rows 6050000 → 6100000
Saved rows 6100000 → 6150000
Saved rows 6150000 → 6200000
Saved rows 6200000 → 6250000
Saved rows 6250000 → 6300000
Saved rows 6300000 → 6350000
Saved rows 6350000 → 6400000
Saved rows 6400000 → 6450000
Saved rows 6450000 → 6500000
Saved rows 6500000 → 6550000
Saved rows 6550000 → 6600000
Saved rows 6600000 → 6650000
Saved rows 6650000 → 6700000
Saved rows 6700000 → 6750000
Saved rows 6750000 → 6800000
Saved rows 6800000 → 6850000
Saved rows 6850000 → 6900000
Saved rows 6900000 → 6950000
Saved rows 6950000 → 7000000
Saved rows 7000000 → 7050000
Saved rows 7050000 → 7100000
Saved rows 7100000 → 7150000
Saved rows 7150000 → 7200000
Saved rows 7200000 → 7250000
Saved rows 7250000 → 7300000
Saved rows 7300000 → 7350000
Saved rows 7350000 → 7400000
Saved rows 7400000 → 7450000
Saved rows 7450000 → 7500000
Saved rows 7500000 → 7550000
Saved rows 7550000 → 7600000
Saved rows 7600000 → 7650000
Saved rows 7650000 → 7700000
Saved rows 7700000 → 7750000
Saved rows 7750000 → 7800000
Saved rows 7800000 → 7850000
Saved rows 7850000 → 7900000
Saved rows 7900000 → 7950000
Saved rows 7950000 → 8000000
Saved rows 8000000 → 8050000
Saved rows 8050000 → 8100000
Saved rows 8100000 → 8150000
Saved rows 8150000 → 8200000
Saved rows 8200000 → 8250000
Saved rows 8250000 → 8300000
Saved rows 8300000 → 8350000
Saved rows 8350000 → 8400000
Saved rows 8400000 → 8450000
Saved rows 8450000 → 8500000
Saved rows 8500000 → 8550000
Saved rows 8550000 → 8600000
Saved rows 8600000 → 8650000
Saved rows 8650000 → 8700000
Saved rows 8700000 → 8750000
Saved rows 8750000 → 8800000
Saved rows 8800000 → 8850000
Saved rows 8850000 → 8900000
Saved rows 8900000 → 8950000
Saved rows 8950000 → 9000000
Saved rows 9000000 → 9050000
Saved rows 9050000 → 9100000
Saved rows 9100000 → 9150000
Saved rows 9150000 → 9200000
Saved rows 9200000 → 9250000
Saved rows 9250000 → 9300000
Saved rows 9300000 → 9350000
Saved rows 9350000 → 9400000
Saved rows 9400000 → 9450000
Saved rows 9450000 → 9500000
Saved rows 9500000 → 9550000
Saved rows 9550000 → 9600000
Saved rows 9600000 → 9650000
Saved rows 9650000 → 9700000
Saved rows 9700000 → 9750000
Saved rows 9750000 → 9800000
Saved rows 9800000 → 9850000
Saved rows 9850000 → 9900000
Saved rows 9900000 → 9950000
Saved rows 9950000 → 10000000
Saved rows 10000000 → 10050000
Saved rows 10050000 → 10100000
Saved rows 10100000 → 10150000
Saved rows 10150000 → 10200000
Saved rows 10200000 → 10250000
Saved rows 10250000 → 10300000
Saved rows 10300000 → 10350000
Saved rows 10350000 → 10400000
Saved rows 10400000 → 10450000
Saved rows 10450000 → 10500000
Saved rows 10500000 → 10550000
Saved rows 10550000 → 10600000
Saved rows 10600000 → 10650000
Saved rows 10650000 → 10700000
Saved rows 10700000 → 10750000
Saved rows 10750000 → 10800000
Saved rows 10800000 → 10850000
Saved rows 10850000 → 10900000
Saved rows 10900000 → 10950000
Saved rows 10950000 → 11000000
Saved rows 11000000 → 11050000
Saved rows 11050000 → 11100000
Saved rows 11100000 → 11150000
Saved rows 11150000 → 11200000
Saved rows 11200000 → 11250000
Saved rows 11250000 → 11300000
Saved rows 11300000 → 11350000
Saved rows 11350000 → 11400000
Saved rows 11400000 → 11450000
Saved rows 11450000 → 11500000
Saved rows 11500000 → 11550000
Saved rows 11550000 → 11600000
Saved rows 11600000 → 11650000
Saved rows 11650000 → 11700000
Saved rows 11700000 → 11750000
Saved rows 11750000 → 11800000
Saved rows 11800000 → 11850000
Saved rows 11850000 → 11900000
Saved rows 11900000 → 11950000
Saved rows 11950000 → 12000000
Saved rows 12000000 → 12050000
Saved rows 12050000 → 12100000
Saved rows 12100000 → 12150000
Saved rows 12150000 → 12200000
Saved rows 12200000 → 12250000
Saved rows 12250000 → 12300000
Saved rows 12300000 → 12350000
Saved rows 12350000 → 12400000
Saved rows 12400000 → 12450000
Saved rows 12450000 → 12500000
Saved rows 12500000 → 12550000
Saved rows 12550000 → 12600000
Saved rows 12600000 → 12650000
Saved rows 12650000 → 12700000
Saved rows 12700000 → 12750000
Saved rows 12750000 → 12800000
Saved rows 12800000 → 12850000
Saved rows 12850000 → 12900000
Saved rows 12900000 → 12950000
Saved rows 12950000 → 13000000
Saved rows 13000000 → 13050000
Saved rows 13050000 → 13100000
Saved rows 13100000 → 13150000
Saved rows 13150000 → 13200000
Saved rows 13200000 → 13250000
Saved rows 13250000 → 13300000
Saved rows 13300000 → 13350000
Saved rows 13350000 → 13400000
Saved rows 13400000 → 13450000
Saved rows 13450000 → 13500000
Saved rows 13500000 → 13550000
Saved rows 13550000 → 13600000
Saved rows 13600000 → 13650000
Saved rows 13650000 → 13700000
Saved rows 13700000 → 13750000
Saved rows 13750000 → 13800000
Saved rows 13800000 → 13850000
Saved rows 13850000 → 13900000
Saved rows 13900000 → 13950000
Saved rows 13950000 → 14000000
Saved rows 14000000 → 14050000
Saved rows 14050000 → 14100000
Saved rows 14100000 → 14150000
Saved rows 14150000 → 14200000
Saved rows 14200000 → 14250000
Saved rows 14250000 → 14300000
Saved rows 14300000 → 14350000
Saved rows 14350000 → 14400000
Saved rows 14400000 → 14450000
Saved rows 14450000 → 14500000
Saved rows 14500000 → 14550000
Saved rows 14550000 → 14600000
Saved rows 14600000 → 14650000
Saved rows 14650000 → 14700000
Saved rows 14700000 → 14750000
Saved rows 14750000 → 14800000
Saved rows 14800000 → 14850000
Saved rows 14850000 → 14900000
Saved rows 14900000 → 14950000
Saved rows 14950000 → 15000000
Saved rows 15000000 → 15050000
Saved rows 15050000 → 15100000
Saved rows 15100000 → 15150000
Saved rows 15150000 → 15200000
Saved rows 15200000 → 15250000
Saved rows 15250000 → 15300000
Saved rows 15300000 → 15350000
Saved rows 15350000 → 15400000
Saved rows 15400000 → 15450000
Saved rows 15450000 → 15500000
Saved rows 15500000 → 15550000
Saved rows 15550000 → 15600000
Saved rows 15600000 → 15650000
Saved rows 15650000 → 15700000
Saved rows 15700000 → 15750000
Saved rows 15750000 → 15800000
Saved rows 15800000 → 15850000
Saved rows 15850000 → 15900000
Saved rows 15900000 → 15950000
Saved rows 15950000 → 16000000
Saved rows 16000000 → 16050000
Saved rows 16050000 → 16100000
Saved rows 16100000 → 16150000
Saved rows 16150000 → 16200000
Saved rows 16200000 → 16250000
Saved rows 16250000 → 16300000
Saved rows 16300000 → 16350000
Saved rows 16350000 → 16400000
Saved rows 16400000 → 16450000
Saved rows 16450000 → 16500000
Saved rows 16500000 → 16550000
Saved rows 16550000 → 16600000
Saved rows 16600000 → 16650000
Saved rows 16650000 → 16700000
Saved rows 16700000 → 16750000
Saved rows 16750000 → 16800000
Saved rows 16800000 → 16850000
Saved rows 16850000 → 16900000
Saved rows 16900000 → 16950000
Saved rows 16950000 → 17000000
Saved rows 17000000 → 17050000
Saved rows 17050000 → 17100000
Saved rows 17100000 → 17150000
Saved rows 17150000 → 17200000
Saved rows 17200000 → 17250000
Saved rows 17250000 → 17300000
Saved rows 17300000 → 17350000
Saved rows 17350000 → 17400000
Saved rows 17400000 → 17450000
Saved rows 17450000 → 17500000
Saved rows 17500000 → 17550000
Saved rows 17550000 → 17600000
Saved rows 17600000 → 17650000
Saved rows 17650000 → 17700000
Saved rows 17700000 → 17750000
Saved rows 17750000 → 17800000
Saved rows 17800000 → 17850000
Saved rows 17850000 → 17900000
Saved rows 17900000 → 17950000
Saved rows 17950000 → 18000000
Saved rows 18000000 → 18050000
Saved rows 18050000 → 18100000
Saved rows 18100000 → 18150000
Saved rows 18150000 → 18200000
Saved rows 18200000 → 18250000
Saved rows 18250000 → 18300000
Saved rows 18300000 → 18350000
Saved rows 18350000 → 18400000
Saved rows 18400000 → 18450000
Saved rows 18450000 → 18500000
Saved rows 18500000 → 18550000
Saved rows 18550000 → 18600000
Saved rows 18600000 → 18650000
Saved rows 18650000 → 18700000
Saved rows 18700000 → 18750000
Saved rows 18750000 → 18800000
Saved rows 18800000 → 18850000
Saved rows 18850000 → 18900000
Saved rows 18900000 → 18950000
Saved rows 18950000 → 19000000
Saved rows 19000000 → 19050000
Saved rows 19050000 → 19100000
Saved rows 19100000 → 19150000
Saved rows 19150000 → 19200000
Saved rows 19200000 → 19250000
Saved rows 19250000 → 19300000
Saved rows 19300000 → 19350000
Saved rows 19350000 → 19400000
Saved rows 19400000 → 19450000
Saved rows 19450000 → 19500000
Saved rows 19500000 → 19550000
Saved rows 19550000 → 19600000
Saved rows 19600000 → 19650000
Saved rows 19650000 → 19700000
Saved rows 19700000 → 19750000
Saved rows 19750000 → 19800000
Saved rows 19800000 → 19850000
Saved rows 19850000 → 19900000
Saved rows 19900000 → 19950000
Saved rows 19950000 → 20000000
Saved rows 20000000 → 20050000
Saved rows 20050000 → 20100000
Saved rows 20100000 → 20150000
Saved rows 20150000 → 20200000
Saved rows 20200000 → 20250000
Saved rows 20250000 → 20300000
Saved rows 20300000 → 20350000
Saved rows 20350000 → 20400000
Saved rows 20400000 → 20450000
Saved rows 20450000 → 20500000
Saved rows 20500000 → 20550000
Saved rows 20550000 → 20600000
Saved rows 20600000 → 20650000
Saved rows 20650000 → 20700000
Saved rows 20700000 → 20750000
Saved rows 20750000 → 20800000
Saved rows 20800000 → 20850000
Saved rows 20850000 → 20900000
Saved rows 20900000 → 20950000
Saved rows 20950000 → 21000000
Saved rows 21000000 → 21050000
Saved rows 21050000 → 21100000
Saved rows 21100000 → 21150000
Saved rows 21150000 → 21200000
Saved rows 21200000 → 21250000
Saved rows 21250000 → 21300000
Saved rows 21300000 → 21350000
Saved rows 21350000 → 21400000
Saved rows 21400000 → 21450000
Saved rows 21450000 → 21500000
Saved rows 21500000 → 21550000
Saved rows 21550000 → 21600000
Saved rows 21600000 → 21650000
Saved rows 21650000 → 21700000
Saved rows 21700000 → 21750000
Saved rows 21750000 → 21800000
Saved rows 21800000 → 21850000
Saved rows 21850000 → 21900000
Saved rows 21900000 → 21950000
Saved rows 21950000 → 22000000
Saved rows 22000000 → 22050000
Saved rows 22050000 → 22100000
Saved rows 22100000 → 22150000
Saved rows 22150000 → 22200000
Saved rows 22200000 → 22250000
Saved rows 22250000 → 22300000
Saved rows 22300000 → 22350000
Saved rows 22350000 → 22400000
Saved rows 22400000 → 22450000
Saved rows 22450000 → 22500000
Saved rows 22500000 → 22550000
Saved rows 22550000 → 22600000
Saved rows 22600000 → 22650000
Saved rows 22650000 → 22700000
Saved rows 22700000 → 22750000
Saved rows 22750000 → 22800000
Saved rows 22800000 → 22850000
Saved rows 22850000 → 22900000
Saved rows 22900000 → 22950000
Saved rows 22950000 → 23000000
Saved rows 23000000 → 23050000
Saved rows 23050000 → 23100000
Saved rows 23100000 → 23150000
Saved rows 23150000 → 23200000
Saved rows 23200000 → 23250000
Saved rows 23250000 → 23300000
Saved rows 23300000 → 23350000
Saved rows 23350000 → 23400000
Saved rows 23400000 → 23450000
Saved rows 23450000 → 23500000
Saved rows 23500000 → 23550000
Saved rows 23550000 → 23600000
Saved rows 23600000 → 23650000
Saved rows 23650000 → 23700000
Saved rows 23700000 → 23750000
Saved rows 23750000 → 23800000
Saved rows 23800000 → 23850000
Saved rows 23850000 → 23900000
Saved rows 23900000 → 23950000
Saved rows 23950000 → 24000000
Saved rows 24000000 → 24050000
Saved rows 24050000 → 24100000
Saved rows 24100000 → 24150000
Saved rows 24150000 → 24200000

In [12]:
dataFrame.columns

Index(['u', 'v', 'length_m', 'timestamp', 'hour', 'day_of_week',
       'current_speed', 'free_flow_speed', 'congestion', 'rain', 'incident',
       'hour_sine', 'hour_cos', 'day_sin', 'day_cos', 'travel_time_log',
       'length_log', 'speed_ratio'],
      dtype='str')

In [13]:
dataFrame.head()

,u,v,length_m,timestamp,hour,day_of_week,current_speed,free_flow_speed,congestion,rain,incident,hour_sine,hour_cos,day_sin,day_cos,travel_time_log,length_log,speed_ratio
14616672,30610511.0,1.541914e+09,9.2531,2024-01-01 00:00:00,0,0,30.6618,40.0,0.2335,0.0,0.0,0.000000,1.000000,0.0,1.0,0.735440,2.32758,0.766545
14616673,30610511.0,1.541914e+09,9.2531,2024-01-01 01:00:00,1,0,25.2321,40.0,0.3692,0.0,0.0,0.258819,0.965926,0.0,1.0,0.841653,2.32758,0.630802
14616674,30610511.0,1.541914e+09,9.2531,2024-01-01 02:00:00,2,0,21.7774,40.0,0.4556,0.0,0.0,0.500000,0.866025,0.0,1.0,0.928061,2.32758,0.544435
14616675,30610511.0,1.541914e+09,9.2531,2024-01-01 03:00:00,3,0,19.7046,40.0,0.5074,0.0,0.0,0.707107,0.707107,0.0,1.0,0.989727,2.32758,0.492615
14616676,30610511.0,1.541914e+09,9.2531,2024-01-01 04:00:00,4,0,18.6461,40.0,0.5338,0.0,0.0,0.866025,0.500000,0.0,1.0,1.024786,2.32758,0.466153